In [6]:
import tensorflow as tf
import numpy as np

# Using a sample imdb dataset from keras datasets

In [8]:
(X, Y), (X_Test, Y_Test) = tf.keras.datasets.imdb.load_data(num_words=30000)

# Every sample point is an array of indexes

In [ ]:
X[0]

# We can get the index to word dictionary invert it and use it to translate from tokens indexes to words

In [9]:
word_to_index = tf.keras.datasets.imdb.get_word_index()

In [10]:
index_to_word = dict([(index, word) for word, index  in word_to_index.items()])

In [11]:
" ".join([index_to_word[token] for token in X[0]])

"the as you with out themselves powerful lets loves their becomes reaching had journalist of lot from anyone to have after out atmosphere never more room titillate it so heart shows to years of every never going villaronga help moments or of every chest visual movie except her was several of enough more with is now current film as you of mine potentially unfortunately of you than him that with out themselves her get for was camp of you movie sometimes movie that with scary but pratfalls to story wonderful that in seeing in character to of 70s musicians with heart had shadows they of here that with her serious to have does when from why what have critics they is you that isn't one will very to as itself with other tricky in of seen over landed for anyone of and br show's to whether from than out themselves history he name half some br of 'n odd was two most of mean for 1 any an boat she he should is thought frog but of script you not while history he heart to real at barrel but when fro

In [15]:
def index_to_text_sentences(X):
    """
     Args X : a list of token indexes
     returns : a list of text sentences
    """
    
    word_to_index = tf.keras.datasets.imdb.get_word_index()
    index_to_word = dict([(index, word) for word, index  in word_to_index.items()])
    
    X_Text = []
    for sentence_index in X:
        text = " ".join([index_to_word[token] for token in sentence_index])
        X_Text.append(text)
    
    return X_Text

In [16]:
X_Text = index_to_text_sentences(X)

In [ ]:
print(f"Shape array : {X_Text.shape}")
print(f"Shape per sample : {X_Text[0].shape}")
print(X_Test[0])

In [17]:
# tf.keras.preprocessing.text.Tokenizer(
#     num_words=None,
#     filters='!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n',
#     lower=True,
#     split=' ',
#     char_level=False,
#     oov_token=None,
#     analyzer=None,
#     **kwargs
# )

In [18]:
tokenizer = tf.keras.preprocessing.text.Tokenizer( 
    num_words = 20000,
    oov_token = "[UNK]",
    char_level=None,
    split=" "
)

In [19]:
tokenizer.fit_on_texts(X_Text)

In [20]:
X_Text[0][:10]

'the as you'

In [21]:
# YOU NEED TO FUCKING SPLIT THE SHIT OUT ??? 

In [22]:
tokenizer.texts_to_sequences([X_Text[0][:10].split(" ")])

[[31, 13, 21]]

In [23]:
next(iter(tokenizer.sequences_to_texts_generator([[31], [13], [21]])))

'the'

In [24]:
tokenizer.texts_to_matrix(["cuando nos vamos?".split(" ")])

array([[0., 1., 0., ..., 0., 0., 0.]])

In [25]:
tokenizer.sequences_to_texts("cuando nos vamos?".split(" "))

['[UNK] [UNK] [UNK] [UNK] [UNK] [UNK]',
 '[UNK] [UNK] [UNK]',
 '[UNK] [UNK] [UNK] [UNK] [UNK] [UNK]']

# Only accepts fucking ints

In [26]:
# tf.keras.utils.pad_sequences(
#     sequences,
#     maxlen=None,
#     dtype='int32',
#     padding='pre',
#     truncating='pre',
#     value=0.0
# )

tf.keras.preprocessing.sequence.pad_sequences([[31], [13], [21]], maxlen=10, padding="post", truncating="post")

array([[31,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [13,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [21,  0,  0,  0,  0,  0,  0,  0,  0,  0]], dtype=int32)

In [27]:
def preprocess_text(text):
    tokenized_text = tokenizer.texts_to_sequences([text.split(" ")])
    return tf.keras.preprocessing.sequence.pad_sequences(tokenized_text, maxlen=20, padding="post", truncating="post")

In [28]:
tf.keras.preprocessing.sequence.pad_sequences([["asdad"], ["ada asd aasd"], ["aas"]], maxlen=2, padding="post", truncating="post", dtype="object")

array([['asdad', 0.0],
       ['ada asd aasd', 0.0],
       ['aas', 0.0]], dtype=object)

In [29]:
preprocess_text("this text is for testing only")

array([[  10, 3005,    4,   14, 7757,   61,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0]],
      dtype=int32)

In [67]:
X_Train = []

for sentence in X_Text:
    X_Train.append(preprocess_text(sentence)[0])

In [68]:
import numpy as np

In [69]:
X_Train = np.array(X_Train, dtype="int32")

In [72]:
X_Train.reshape([-1, 600, 1])

ValueError: cannot reshape array of size 500000 into shape (600,1)

In [62]:
X_Train[0]

array([[  31],
       [  13],
       [  21],
       [  15],
       [  43],
       [ 529],
       [ 971],
       [1621],
       [1384],
       [  65],
       [ 458],
       [4452],
       [  66],
       [3933],
       [   2],
       [ 173],
       [  36],
       [ 256],
       [   3],
       [  24]], dtype=int32)

In [48]:
X_Train[0]

array([  31,   13,   21,   15,   43,  529,  971, 1621, 1384,   65,  458,
       4452,   66, 3933,    2,  173,   36,  256,    3,   24], dtype=int32)

In [34]:
dataset = tf.data.Dataset.from_tensor_slices((X_Train, Y)).batch(1).prefetch(tf.data.AUTOTUNE)

2023-06-22 23:53:06.667704: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-06-22 23:53:06.672754: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-06-22 23:53:06.673462: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-06-22 23:53:06.674121: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags

In [35]:
next(iter(dataset))

(<tf.Tensor: shape=(1, 1, 20), dtype=int32, numpy=
 array([[[  31,   13,   21,   15,   43,  529,  971, 1621, 1384,   65,
           458, 4452,   66, 3933,    2,  173,   36,  256,    3,   24]]],
       dtype=int32)>,
 <tf.Tensor: shape=(1,), dtype=int64, numpy=array([1])>)

In [53]:
Y.reshape(-1, 1).shape

(25000, 1)

In [76]:
vectorizer_layer = tf.keras.layers.TextVectorization(max_tokens=20000, pad_to_max_tokens=True, output_sequence_length=600)

In [77]:
vectorizer_layer.adapt(X_Text)

In [81]:
result_tokenized = vectorizer_layer(X_Text)

In [82]:
result_tokenized.shape

TensorShape([25000, 600])

In [83]:
X_Train.shape

(25000, 20)

In [87]:
result_tokenized[0].numpy().shape

(600,)

In [86]:
X_Train[0].shape

(20,)