In [1]:
from zipfile import ZipFile
import os
import tensorflow as tf
import pandas as pd

uri = "https://storage.googleapis.com/tensorflow/tf-keras-datasets/jena_climate_2009_2016.csv.zip"
zip_path = tf.keras.utils.get_file(origin=uri, fname="jena_climate_2009_2016.csv.zip")
zip_file = ZipFile(zip_path)
zip_file.extractall()
csv_path = "jena_climate_2009_2016.csv"

df = pd.read_csv(csv_path)

2023-07-13 18:55:43.311740: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-07-13 18:55:43.410681: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-07-13 18:55:43.874969: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-07-13 18:55:43.875008: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or 

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 420551 entries, 0 to 420550
Data columns (total 15 columns):
 #   Column           Non-Null Count   Dtype  
---  ------           --------------   -----  
 0   Date Time        420551 non-null  object 
 1   p (mbar)         420551 non-null  float64
 2   T (degC)         420551 non-null  float64
 3   Tpot (K)         420551 non-null  float64
 4   Tdew (degC)      420551 non-null  float64
 5   rh (%)           420551 non-null  float64
 6   VPmax (mbar)     420551 non-null  float64
 7   VPact (mbar)     420551 non-null  float64
 8   VPdef (mbar)     420551 non-null  float64
 9   sh (g/kg)        420551 non-null  float64
 10  H2OC (mmol/mol)  420551 non-null  float64
 11  rho (g/m**3)     420551 non-null  float64
 12  wv (m/s)         420551 non-null  float64
 13  max. wv (m/s)    420551 non-null  float64
 14  wd (deg)         420551 non-null  float64
dtypes: float64(14), object(1)
memory usage: 48.1+ MB


In [3]:
df.head()

Date Time  p (mbar)  T (degC)  Tpot (K)  Tdew (degC)  rh (%)  \
0  01.01.2009 00:10:00    996.52     -8.02    265.40        -8.90    93.3   
1  01.01.2009 00:20:00    996.57     -8.41    265.01        -9.28    93.4   
2  01.01.2009 00:30:00    996.53     -8.51    264.91        -9.31    93.9   
3  01.01.2009 00:40:00    996.51     -8.31    265.12        -9.07    94.2   
4  01.01.2009 00:50:00    996.51     -8.27    265.15        -9.04    94.1   

   VPmax (mbar)  VPact (mbar)  VPdef (mbar)  sh (g/kg)  H2OC (mmol/mol)  \
0          3.33          3.11          0.22       1.94             3.12   
1          3.23          3.02          0.21       1.89             3.03   
2          3.21          3.01          0.20       1.88             3.02   
3          3.26          3.07          0.19       1.92             3.08   
4          3.27          3.08          0.19       1.92             3.09   

   rho (g/m**3)  wv (m/s)  max. wv (m/s)  wd (deg)  
0       1307.75      1.03           1.75     152.3  
1       1309.80      0.72           1.50     136.1  
2       1310.24      0.19           0.63     171.6  
3       1309.19      0.34           0.50     198.0  
4       1309.00      0.32           0.63     214.3

In [13]:
import numpy as np
data = []

with open("jena_climate_2009_2016.csv") as f:
    for index, row in enumerate(f):
        if index>0:
            line = [float(c) for c in row.split(sep=",")[1:]]
            data.append(line)
        else:
            headers = row.split(sep=",")[1:]

In [14]:
data[:5]

[[996.52,
  -8.02,
  265.4,
  -8.9,
  93.3,
  3.33,
  3.11,
  0.22,
  1.94,
  3.12,
  1307.75,
  1.03,
  1.75,
  152.3],
 [996.57,
  -8.41,
  265.01,
  -9.28,
  93.4,
  3.23,
  3.02,
  0.21,
  1.89,
  3.03,
  1309.8,
  0.72,
  1.5,
  136.1],
 [996.53,
  -8.51,
  264.91,
  -9.31,
  93.9,
  3.21,
  3.01,
  0.2,
  1.88,
  3.02,
  1310.24,
  0.19,
  0.63,
  171.6],
 [996.51,
  -8.31,
  265.12,
  -9.07,
  94.2,
  3.26,
  3.07,
  0.19,
  1.92,
  3.08,
  1309.19,
  0.34,
  0.5,
  198.0],
 [996.51,
  -8.27,
  265.15,
  -9.04,
  94.1,
  3.27,
  3.08,
  0.19,
  1.92,
  3.09,
  1309.0,
  0.32,
  0.63,
  214.3]]

In [15]:
dataset = np.array(data, dtype="float16")

In [17]:
dataset[:2]

array([[ 9.965e+02, -8.023e+00,  2.655e+02, -8.898e+00,  9.331e+01,
         3.330e+00,  3.109e+00,  2.200e-01,  1.940e+00,  3.119e+00,
         1.308e+03,  1.030e+00,  1.750e+00,  1.522e+02],
       [ 9.965e+02, -8.406e+00,  2.650e+02, -9.281e+00,  9.338e+01,
         3.230e+00,  3.020e+00,  2.100e-01,  1.890e+00,  3.029e+00,
         1.310e+03,  7.202e-01,  1.500e+00,  1.361e+02]], dtype=float16)

In [26]:
dataset[:, 1][:5]

array([-8.02, -8.41, -8.51, -8.31, -8.27], dtype=float16)

In [27]:
with open("jena_climate_2009_2016.csv") as f:
    for index, row in enumerate(f):
        if index > 0:
            line = [float(c) for c in row.split(sep=",")[1:]]
            data.append(line)
        else:
            headers = row.split(sep=",")[1:]

dataset = np.array(data, dtype="float16")

# take only temperature
dataset = dataset[:, 1]

print(dataset[:5])

[-8.02 -8.41 -8.51 -8.31 -8.27]
